[project]
name = "linkedin-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julio Leite", email = "julio@agenciafrato.com.br" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
linkedin-langchain = "linkedin_langchain:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
